URL = {
    "protenix-v2": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix-v2.pt",
    "protenix_base_default_v1.0.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_base_default_v1.0.0.pt",
    "protenix_base_20250630_v1.0.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_base_20250630_v1.0.0.pt",
    "protenix_base_default_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_base_default_v0.5.0.pt",
    "protenix_base_constraint_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_base_constraint_v0.5.0.pt",
    "protenix_mini_default_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_mini_default_v0.5.0.pt",
    "protenix_tiny_default_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_tiny_default_v0.5.0.pt",
    "protenix_mini_esm_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_mini_esm_v0.5.0.pt",
    "esm2_t36_3B_UR50D": "https://protenix.tos-cn-beijing.volces.com/checkpoint/esm2_t36_3B_UR50D.pt",
    "esm2_t36_3B_UR50D-contact-regression": "https://protenix.tos-cn-beijing.volces.com/checkpoint/esm2_t36_3B_UR50D-contact-regression.pt",
    "protenix_mini_ism_v0.5.0": "https://protenix.tos-cn-beijing.volces.com/checkpoint/protenix_mini_ism_v0.5.0.pt",
    "esm2_t36_3B_UR50D_ism": "https://protenix.tos-cn-beijing.volces.com/checkpoint/esm2_t36_3B_UR50D_ism.pt",
    "esm2_t36_3B_UR50D_ism-contact-regression": "https://protenix.tos-cn-beijing.volces.com/checkpoint/esm2_t36_3B_UR50D_ism-contact-regression.pt",
    "ccd_components_file": "https://protenix.tos-cn-beijing.volces.com/common/components.cif",
    "ccd_components_rdkit_mol_file": "https://protenix.tos-cn-beijing.volces.com/common/components.cif.rdkit_mol.pkl",
    "pdb_cluster_file": "https://protenix.tos-cn-beijing.volces.com/common/clusters-by-entity-40.txt",
    "obsolete_release_data_csv": "https://protenix.tos-cn-beijing.volces.com/common/obsolete_release_date.csv",
    "obsolete_pdbs_path": "https://protenix.tos-cn-beijing.volces.com/common/obsolete_to_successor.json",
    "release_dates_path": "https://protenix.tos-cn-beijing.volces.com/common/release_date_cache.json",
}
